#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("./slimstk.php");
slimstk_cmd_init ();

$argv = $_SERVER['argv'];

$stkname = trim (@$argv[1]);

if ($stkname == "") {
	printf ("usage: stack-delete stackname\n");
	exit (1);
}

if ((@$stkinfo = $slimstk['stacks'][$stkname]) == NULL) {
	printf ("unknown stack %s for account %s\n",
		$stkname, $slimstk['aws_acct_name']);
	exit (1);
}
slimstk_set_region ($stkinfo['region']);

$template = sprintf ("%s/stack-%s.json", $slimstk['confdir'], $stkname);

if (! file_exists ($template)) {
	printf ("%s not found, run:\n", $template);
	printf ("./stack-config %s\n", $stkname);
	exit (1);
}



$args = array ("cloudformation", "delete-stack");
$args[] = "--stack-name";
$args[] = $stkname;
$val = slimstk_aws ($args);
printf ("%s\n", json_encode ($val));


 

