#! /bin/sh -xe

# running in /opt/codedeploy-agent as ec2-user
# nothing useful in args or environment
# $0 is full path to this script in /opt/codedeploy-agent/deployment-root/...
#
# output from this script goes to a file like
# /opt/codedeploy-agent/deployment-root/1c0.../d-8MW.../logs/scripts.log


deploy_dir=`dirname $0`

date
echo "deploy from ${deploy_dir}"

cd ${deploy_dir}

dest_name=`cat dname`

dest_dir=/home/ec2-user/${dest_name}
mkdir -p ${dest_dir}

tar -C ${dest_dir} -xf app.tar
cp commit ${dest_dir}/website/.

cd ${dest_dir}
./install-site
if [ $? != 0 ]
then
    echo "error running install-site"
    exit 1
fi

sh ${deploy_dir}/tagcmd

siteid=`echo $dest_name | sed 's/[.].*//'`
rm -f /home/ec2-user/${siteid}
ln -sf ${dest_name} /home/ec2-user/${siteid}

