#! /bin/sh -x

# call to this script is set up in ./stack-config
# arg is region
# user is ec2-user
# sudo works

region=$1

id
pwd
env

instdir=$HOME/slimstk-inst

mkdir -p $HOME/.ssh
chmod 700 $HOME/.ssh
cp ${instdir}/authorized_keys $HOME/.ssh/authorized_keys

chmod a+rx $HOME
sudo chown ec2-user $instdir

if [ -d $HOME/slimstk ]
then
    # development mode
    cd $HOME/slimstk
else
    # we're running from cloudformation
    cd $HOME/slimstk-inst
fi

sudo ln -s ${instdir} /var/slimstk

sudo mkdir -p /www/blank
sudo cp /dev/null /www/blank/index.html

mkdir -p $HOME/sites-enabled

grep '# slimstk config' /etc/httpd/conf/httpd.conf > /dev/null 2>&1
if [ $? != 0 ]
then
    sudo sh -c "cat $HOME/slimstk-inst/httpd-extra.conf \
 >> /etc/httpd/conf/httpd.conf"
fi

./inst-phpinit

bucket=aws-codedeploy-${region}
src="s3://${bucket}/latest/install"
dst=/tmp/codedeploy-install
aws s3 cp $src $dst
chmod a+x $dst

# gratuitous 3 minute sleep, so put in background 
sudo $dst rpm &

exit 0
