#! /bin/sh -x

# user is ec2-user
# sudo works

instdir=$HOME/slimstk-inst

mkdir -p $HOME/.ssh
chmod 700 $HOME/.ssh
cp ${instdir}/authorized_keys $HOME/.ssh/authorized_keys

chmod a+rx $HOME
sudo chown ec2-user $instdir

if [ -d $HOME/slimstk ]
then
    # development mode
    cd $HOME/slimstk
else
    # we're running from cloudformation
    cd $HOME/slimstk-inst
fi

sudo mkdir -p /var/slimstk
sudo chown -R ec2-user /var/slimstk
cp $instdir/slimstk.php $instdir/stacks.json /var/slimstk

sudo mkdir -p /www/blank
sudo cp /dev/null /www/blank/index.html

mkdir -p $HOME/sites-enabled

grep '# slimstk config' /etc/httpd/conf/httpd.conf > /dev/null 2>&1
if [ $? != 0 ]
then
    sudo sh -c "cat $HOME/slimstk-inst/httpd-extra.conf \
 >> /etc/httpd/conf/httpd.conf"
fi

./inst-phpinit

exit 0
