#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("/var/slimstk/slimstkcmd.php");
slimstk_cmd_init ();

printf ("setup for stack %s\n", $stkname);

$region = $stkinfo['region'];
slimstk_set_region ($region);

$instdir = sprintf ("%s/slimstk-inst", $_SERVER['HOME']);

function setup_dns () {
	global $slimstk, $stkname, $stkinfo;

	if (($server_domain = @$stkinfo['server_domain']) == "")
		return;

	$hosted_zone_id = slimstk_get_hosted_zone_id ($server_domain);
	if ($hosted_zone_id == "") {
		printf ("setup_dns: server_domain %s not found in route53\n",
			$server_domain);
		return;
	}

	$val = slimstk_get_aws_param ("/meta-data/placement/availability-zone");
	$zone_letter = substr ($val, -1);

	$public_ipv4 = slimstk_get_aws_param ("/meta-data/public-ipv4");

	$abs_name = sprintf ("%s%s.%s.",
			     $stkname, $zone_letter, $server_domain);

	printf ("%s => %s\n", $abs_name, $public_ipv4);

	$items = array ();
	$items[] = array ("Action" => "UPSERT", 
			  "ResourceRecordSet" => array (
				  "Name" => $abs_name, 
				  "Type" => "A", 
				  "TTL" => 30, 
				  "ResourceRecords" => array (
					  array ("Value" => $public_ipv4)
					  )
				  )
		);

	$change_batch = array ("Changes" => $items);

	$args = array ("route53", "change-resource-record-sets");
	$args[] = "--hosted-zone-id";
	$args[] = $hosted_zone_id;
	$args[] = "--change-batch";
	$args[] = json_encode ($change_batch);
	slimstk_aws ($args);
}

function decrypt_files () {
	global $instdir, $stkinfo;

	$desired_suffix = sprintf (".%s.kms", $stkinfo['region']);
	$suffixlen = strlen ($desired_suffix);

	$dir = opendir ($instdir);
	while (($name = readdir ($dir)) != NULL) {
		$kms_name = sprintf ("%s/%s", $instdir, $name);
		$suffix = substr ($kms_name, - $suffixlen);
		if (strcmp ($suffix, $desired_suffix) != 0)
			continue;
		$len = strlen ($kms_name);
		$clear_name = substr ($kms_name, 0, - $suffixlen);
		
		printf ("decrypt %s\n", $kms_name);

		$cmd = sprintf ("aws --region %s kms decrypt"
				." --ciphertext-blob fileb://%s"
				." --query Plaintext"
				." --output text",
				escapeshellarg ($stkinfo['region']),
				escapeshellarg ($kms_name));
		printf("%s\n", $cmd);
		$val_base64 = shell_exec ($cmd);
		$cleartext = base64_decode ($val_base64);
		file_put_contents ($clear_name, $cleartext);
	}
}

function setup_db_access () {
	global $slimstk, $stkname, $stkinfo;
	global $instdir, $region;

	$database = $stkinfo['database'];

	$db_passwd_base = sprintf ("dbpass.%s.%s",
				   $slimstk['aws_acct_name'], $database);

	if (! file_exists ($db_passwd_base)) {
		printf ("%s does not exist\n", $db_passwd_base);
		return;
	}

	$db_passwd = trim (file_get_contents ($db_passwd_base));

	$db_host = slimstk_getvar_region ("dbhost.db");

	$text = sprintf ("[client]\n"
			 ."user=root\n"
			 ."host=%s\n"
			 ."password=%s\n",
			 $db_host, $db_passwd);
	$fname = sprintf ("%s/.my.cnf", $_SERVER['HOME']);
	file_put_contents ($fname, $text);
	chmod ($fname, 0600);

	$text = sprintf ("<?php\n"
			 ."\$default_dbparams = array (\n"
			 ." 'host' => '%s',\n"
			 ." 'user' => 'root',\n"
			 ." 'passwd' => '%s'\n"
			 .");\n",
			 $db_host, $db_passwd);
	file_put_contents ("/var/slimstk/dbparams.php", $text);
}

decrypt_files ();

setup_dns ();
setup_db_access ();
