#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("./slimstk.php");
slimstk_cmd_init ();

function do_stack ($stkname, $stkinfo) {
	global $alternative_ssh_port;

	if (($server_domain = @$stkinfo['server_domain']) == NULL)
		return;

	foreach (array ("a","b","c","d","e") as $zone) {
		$short_hostname = sprintf ("%s%s", $stkname, $zone);
		$long_hostname = sprintf ("%s.%s",
					  $short_hostname, $server_domain);

		$opts = array ();
		$opts[] = sprintf ("Hostname %s", $long_hostname);
		$opts[] = "User ec2-user";
		$opts[] = sprintf ("Port %d", $alternative_ssh_port);
		$opts[] = "StrictHostKeyChecking no";
		$opts[] = "UserKnownHostsFile=/dev/null";

		$desired_short = sprintf ("Host %s\n"
					  ."%s",
					  $short_hostname,
					  implode ("\n", $opts));
		$desired_long = sprintf ("Host %s\n"
					 ."%s",
					 $long_hostname,
					 implode ("\n", $opts));

		$desired_short = trim ($desired_short);
		$desired_long = trim ($desired_long);

		$fname = sprintf ("%s/.ssh/config", $_SERVER['HOME']);
		$old_data = file_get_contents ($fname);
		$val = preg_split ("/^([ \t]*)\$/m", $old_data);
		$new_data = "";

		$did_long = 0;
		$did_short = 0;
		foreach ($val as $row) {
			$row = trim ($row);
			if ($row == "")
				continue;
			if (sscanf ($row, "Host %s", $h) != 1) {
				$new_data .= $row . "\n\n";
			} else if (strcmp ($h, $long_hostname) == 0) {
				$new_data .= $desired_long."\n\n";
				$did_long = 1;
			} else if (strcmp ($h, $short_hostname) == 0) {
				$new_data .= $desired_short."\n\n";
				$did_short = 1;
			} else {
				$new_data .= $row . "\n\n";
			}
		}

		if (! $did_long)
			$new_data .= $desired_long."\n\n";
		if (! $did_short)
			$new_data .= $desired_short."\n\n";

		if (strcmp ($old_data, $new_data) != 0) {
			printf ("updating %s\n", $fname);
			file_put_contents ($fname, $new_data);
		}
	}
}
	
foreach ($slimstk['stacks'] as $stkname => $stkinfo) {
	do_stack ($stkname, $stkinfo);
}
