#! /usr/bin/php
<?php /* -*- mode:php -*- */

if (($confdir = @$_SERVER['argv'][1]) != NULL) {
	$_SERVER['confdir'] = $confdir;
}

require_once ("/opt/slimstk/slimstkcmd.php");
slimstk_init ();

$confdir = $slimstk['confdir'];
$aws_acct_name = $slimstk['aws_acct_name'];

$user = $_SERVER['USER'];

$login_profile = sprintf ("%s-%s", $aws_acct_name, $user);

$awsdir = sprintf ("%s/.aws", $_SERVER['HOME']);
if (! file_exists ($awsdir)) {
	mkdir ($awsdir, 0700);
}
$credfile = sprintf ("%s/credentials", $awsdir);

$creds = array ();

$old_text = @file_get_contents ($credfile);

/* break up by lines that start with left square bracket */
preg_match_all ('/^([[][^[]*)/m', $old_text, $matches);
foreach ($matches[1] as $item) {
	/* find the word insides the square brackets */
	preg_match ('/[[](.*)[]]/', $item, $parts);
	$profile = $parts[1];
	$creds[$profile] = trim ($item);
}

$aws_key_fname = sprintf ("%s/access-key-%s.enc", $confdir, $login_profile);

$cmd = sprintf ("slimstk decrypt %s - 2> /dev/null",
		escapeshellarg ($aws_key_fname));

$text = trim (shell_exec ($cmd));

if ($text == NULL) {
	printf ("error running: %s\n", $cmd);
	printf ("do you need to run this?\n");
	printf ("slimstk agent -b\n");
	exit (1);
}

$key_id = NULL;
$secret = NULL;
if (preg_match ('/aws_access_key_id.*= *(.*)/', $text, $parts))
	$key_id = $parts[1];
if (preg_match ('/aws_secret_access_key.*= *(.*)/', $text, $parts))
	$secret = $parts[1];
$cname = sprintf ("%s/TMP.devel-creds", $confdir);
@unlink ($cname);
file_put_contents ($cname, sprintf ("%s %s\n", $key_id, $secret));

$creds[$login_profile] = $text;

$tname = tempnam ($awsdir, "TMP.");
$outf = fopen ($tname, "w");
foreach ($creds as $profile => $item) {
	fprintf ($outf, "%s\n\n", $item);
}
fclose ($outf);
rename ($tname, $credfile);

$fname = sprintf ("%s/current-confdir", $awsdir);
file_put_contents ($fname, $confdir . "\n");

printf ("ready to use aws account %s\n", $aws_acct_name);
printf ("export AWS_DEFAULT_PROFILE=%s\n", $login_profile);
