#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("/opt/slimstk/slimstkcmd.php");
slimstk_init ();

$confdir = $slimstk['confdir'];
$aws_acct_name = $slimstk['aws_acct_name'];

if (preg_match (':/:', $aws_acct_name)) {
	printf ("invliad account name in %s\n", $aws_acct_name);
	exit (1);
}

$user = $_SERVER['USER'];

$login_profile = sprintf ("%s-%s", $aws_acct_name, $user);

$aws_key_fname = sprintf ("%s/access-key-%s.enc", $confdir, $login_profile);

$stdin = fopen ("php://stdin", "r");

printf ("access_key_id: ");
$access_key_id = trim (fgets ($stdin));
printf ("secret_access_key: ");
$secret_access_key = trim (fgets ($stdin));
	
$text = sprintf ("[%s]\n", $login_profile);
$text .= sprintf ("aws_access_key_id = %s\n", $access_key_id);
$text .= sprintf ("aws_secret_access_key = %s\n",
		  $secret_access_key);
		
$enc_name = sprintf ("%s/access-key-%s-%s.enc",
		     $confdir, $aws_acct_name, $user);
$cmd = sprintf ("slimstk encrypt -u %s - %s",
		escapeshellarg ($user),
		escapeshellarg ($enc_name));
$outf = popen ($cmd, "w");
fwrite ($outf, $text);
pclose ($outf);

if (@filesize ($enc_name) == 0) {
	printf ("error storing %s\n", $enc_name);
	exit (1);
}

printf ("done\n");
