#! /bin/sh -xe

# this runs once upon boot in a new instance
# user is ec2-user
# sudo works

cd $HOME/slimstk-inst

chmod a+rx $HOME

sudo yum -y update aws-cli

sudo chown -R ec2-user /var/slimstk

# cp authorized_keys $HOME/.ssh/authorized_keys

sudo mkdir -p /www/blank
sudo cp /dev/null /var/blank/index.html

mkdir -p $HOME/sites-enabled

grep '# slimstk config' /etc/httpd/conf/httpd.conf > /dev/null 2>&1
if [ $? != 0 ]
then
    sudo sh -c "cat httpd-extra.conf >> /etc/httpd/conf/httpd.conf"
fi

./slimstk-phpinit

exit 0


