#! /usr/bin/php
<?php /* -*- mode:php -*- */

$argv = $_SERVER['argv'];

if (($confdir = trim (@$argv[1])) == "") {
	printf ("usage: slimstk-login confdir\n");
	exit (1);
}

$stacks_name = sprintf ("%s/stacks.json", $confdir);
if (($stacks = @json_decode (file_get_contents ($stacks_name), true)) == NULL) {
	printf ("can't parse %s\n", $stacks_name);
	exit (1);
}

$aws_acct_name = $stacks['aws_acct_name'];

if (preg_match (':/:', $aws_acct_name)) {
	printf ("invliad account name in %s\n", $stacks_name);
	exit (1);
}

$user = $_SERVER['USER'];

if (($gpg_key_id = @$stacks['users'][$user]['gpg_key_id']) == "") {
	printf ("%s doesn't contain a gpg key for %s\n", $stacks_name, $user);
	exit (1);
}

$gpg_name = sprintf ("%s/access-key-%s-%s.gpg",
		     $confdir, $aws_acct_name, $user);

if (! file_exists ($gpg_name)) {
	printf ("need access_key and secret_access_key for %s on %s\n",
		$user, $aws_acct_name);

	$stdin = fopen ("php://stdin", "r");

	printf ("access_key_id: ");
	$access_key_id = trim (fgets ($stdin));
	printf ("secret_access_key: ");
	$secret_access_key = trim (fgets ($stdin));
	
	$text = sprintf ("[%s-%s]\n", $aws_acct_name, $user);
	$text .= sprintf ("aws_access_key_id = %s\n", $access_key_id);
	$text .= sprintf ("aws_secret_access_key = %s\n",
			  $secret_access_key);
		
	$cmd = sprintf ("gpg --encrypt --output %s --recipient %s",
			escapeshellarg ($gpg_name),
			escapeshellarg ($gpg_key_id));
	$f = popen ($cmd, "w");
	fwrite ($f, $text);
	pclose ($f);
	if (@filesize ($gpg_name) == 0) {
		printf ("error storing %s\n", $access_key_gpg);
		exit (1);
	}

	printf ("%s created\n", $gpg_name);
}

$awsdir = sprintf ("%s/.aws", $_SERVER['HOME']);
if (! file_exists ($awsdir)) {
	mkdir ($awsdir, 0700);
}
$credfile = sprintf ("%s/credentials", $awsdir);

$creds = array ();

$old_text = @file_get_contents ($credfile);

/* break up by lines that start with left square bracket */
preg_match_all ('/^([[][^[]*)/m', $old_text, $matches);
foreach ($matches[1] as $item) {
	/* find the word insides the square brackets */
	preg_match ('/[[](.*)[]]/', $item, $parts);
	$profile = $parts[1];
	$creds[$profile] = trim ($item);
}

$cmd = sprintf ("gpg --quiet --decrypt --output - %s",
		escapeshellarg ($gpg_name));

$text = trim (shell_exec ($cmd));

if ($text == NULL) {
	printf ("error running: %s\n", $cmd);
	exit (1);
}

$profile = sprintf ("%s-%s", $aws_acct_name, $user);
$creds[$profile] = $text;

$tname = tempnam ($awsdir, "TMP.");
$outf = fopen ($tname, "w");
foreach ($creds as $profile => $item) {
	fprintf ($outf, "%s\n\n", $item);
}
fclose ($outf);
rename ($tname, $credfile);

printf ("ready to use aws account %s\n", $aws_acct_name);
