#! /bin/sh

if [ $# != 1 ]
then
    echo "usage: ssl-chain-info chainfile"
    exit 1
fi

chainfile=$1

rm -f TMP.chain.*
csplit -s -f TMP.chain. $chainfile '%BEGIN%' '/BEGIN CERTIFICATE/' '{*}'
for cert in TMP.chain.*
do
    echo $cert
    openssl x509 -in $cert -noout -text > $cert.txt
    openssl x509 -in $cert -noout -issuer -subject
    echo ""
done
