#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("./slimstk.php");
slimstk_cmd_init ();

$db_done = array ();
foreach ($slimstk['stacks'] as $stkname => $stkinfo) {
	$database = $stkinfo['database'];
	$region = $stkinfo['region'];

	$pname = sprintf ("%s/dbpass.%s.%s",
			  $slimstk['confdir'],
			  $slimstk['aws_acct_name'],
			  $database);
	$gpg_name = sprintf ("%s.gpg", $pname);
	$kms_name = sprintf ("%s.%s.kms", $pname, $region);

	if (isset ($db_done[$kms_name]))
		continue;
	$db_done[$kms_name] = 1;

	slimstk_make_kms_for_region ($gpg_name, $region);
}
