#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("./slimstk.php");
slimstk_cmd_init ();

function do_kms_encrypt ($region, $gpg_name, $kms_name) {
	global $slimstk;

	$clear_name = "DANGER.clear";
	@unlink ($clear_name);
	$cmd = sprintf ("gpg --decrypt --output %s %s",
			$clear_name, $gpg_name);
	system ($cmd, $rc);
	if ($rc != 0) {
		printf ("error running: %s\n", $cmd);
		exit (1);
	}

	$kms_key_id = sprintf ("alias/%s", $slimstk['aws_acct_name']);

	slimstk_set_region ($region);
	$args = array ("kms", "encrypt");
	$args[] = "--key-id";
	$args[] = $kms_key_id;
	$args[] = "--plaintext";
	$args[] = sprintf ("file://%s", $clear_name);
	$val = slimstk_aws ($args);
	unlink ($clear_name);
	$encrypted = base64_decode ($val['CiphertextBlob']);
	printf ("writing %s\n", $kms_name);
	file_put_contents ($kms_name, $encrypted);
}

$db_done = array ();
foreach ($slimstk['stacks'] as $stkname => $stkinfo) {
	$database = $stkinfo['database'];
	$region = $stkinfo['region'];

	$pname = sprintf ("%s/dbpass.%s.%s",
			  $slimstk['confdir'],
			  $slimstk['aws_acct_name'],
			  $database);
	$gpg_name = sprintf ("%s.gpg", $pname);
	$kms_name = sprintf ("%s.%s.kms", $pname, $region);

	if (isset ($db_done[$kms_name]))
		continue;
	$db_done[$kms_name] = 1;

	if (! file_exists ($gpg_name)) {
		printf ("%s does not exist, you need:\n");
		printf ("./setup-aws-acct\n");
		exit (1);
	}

	do_kms_encrypt ($region, $gpg_name, $kms_name);
}

$key_done = array ();
foreach ($slimstk['stacks'] as $stkname => $stkinfo) {
	$region = $stkinfo['region'];

	foreach ($stkinfo['sites'] as $siteid => $sinfo) {
		$app_name = preg_replace ('/-.*/', '', $siteid);

		$basename = sprintf ("%s/deploy-%s",
				     $slimstk['confdir'], $app_name);
		$gpg_name = sprintf ("%s.gpg", $basename);
		$kms_name = sprintf ("%s.%s.kms", $basename, $region);

		if (isset ($key_done[$kms_name]))
			continue;
		$key_done[$kms_name] = 1;

		do_kms_encrypt ($region, $gpg_name, $kms_name);
	}
}
	