#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("/opt/slimstk/slimstkcmd.php");
slimstk_init ();

$region_files = array ();

foreach ($slimstk['stacks'] as $stkname => $stkinfo) {
	$region = $stkinfo['region'];
	if (! isset ($region_files[$region]))
		$region_files[$region] = array ();

	$database = $stkinfo['database'];
	$enc_name = sprintf ("%s/dbpass.%s.%s.enc",
			     $slimstk['confdir'],
			     $slimstk['aws_acct_name'],
			     $database);
	$region_files[$region][$enc_name] = 1;

	foreach ($slimstk['files'] as $filename) {
		if (preg_match ('/[.]enc$/', $filename)) {
			$enc_name = sprintf ("%s/%s",
					     $slimstk['confdir'],
					     $filename);
			$region_files[$region][$enc_name] = 1;
		}
			
	}
}

foreach ($region_files as $region => $files) {
	foreach ($files as $enc_name => $dummy) {
		printf ("%s %s\n", $region, $enc_name);
		slimstk_make_kms_for_region ($enc_name, $region);
	}
}
